version: '3'

services:
  mongo:
    image: mongo:4.1.3
    container_name: mongo
  app:
    build:
      context: .
    container_name: app
    environment:
      MONGODB_URI: mongodb://mongo:27017/docker
    depends_on:
      - mongo
