version: '3'

services:
  app:
    working_dir: /app
    command: npm run dev
    volumes:
      - ./back/:/app/
    expose:
      - '8000'
  front:
    build:
      context: .
      args:
        NODE_ENV: development
    container_name: front
    working_dir: /front
    command: npm start -- --port 8000
    environment:
      PROXY_HOST: app
      PORT: '8000'
    volumes:
      - ./front/:/front/
    ports:
      - '8000:8000'
